services:
  db:
    image: mysql
    container_name: ecommerce-app-database
    environment:

      MYSQL_DATABASE: 'ecommerce_v2'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306


    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

    volumes:
      - ecommerce-app_data:/var/lib/mysql

  backend:
    image: leonardorocio/ecommerce-spring-app:latest
    environment:
      MYSQL_HOST: 'db'
    ports:
      - 9000:9000
    
    depends_on:
      db:
        condition: service_healthy
    
  
  frontend:
    image: leonardorocio/ecommerce-angular-app:latest
    ports:
      - 80:80

    depends_on:
      - backend

volumes:
  ecommerce-app_data:
