spring:

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:~/data/ecommerce_v2
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 9000
  error:
    include-stacktrace: never
    include-message: never

jwt:
  secret: '"2A472D4A614E645267556B58703273357638792F423F4528482B4D6250655368"'
  expiration: '700000'
